require("../utils/imports.util").dotenv.config();

module.exports = {
  PORT: process.env.PORT,
  AUTH_SERVICE_URL: process.env.AUTH_SERVICE_URL,
  BOOKING_SERVICE_URL: process.env.BOOKING_SERVICE_URL,
  REMINDER_SERVICE_URL: process.env.REMINDER_SERVICE_URL,
  FLIGHT_AND_SEARCH_SERVICE_URL: process.env.FLIGHT_AND_SEARCH_SERVICE_URL,
  AUTH_SERVICE_PATH: process.env.AUTH_SERVICE_PATH,
  BOOKING_SERVICE_PATH: process.env.BOOKING_SERVICE_PATH,
  REMINDER_SERVICE_PATH: process.env.REMINDER_SERVICE_PATH,
  FLIGHT_AND_SEARCH_SERVICE_PATH: process.env.FLIGHT_AND_SEARCH_SERVICE_PATH,
};
